# Base docker-compose file
version: '3.8'

services:  
  node:
    container_name: lucky-parking-node
    build: ./
    restart: always
    env_file: .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      PORT: ${PORT}
    volumes:
      - ./:/usr/src/app