# AWS Prod instance and AWS Dev instance
version: '3.8'

services:  
  node:
    container_name: lucky-parking-node
    build: ./
    restart: always
    env_file: .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: pgdb
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      PORT: ${PORT}
    ports:
      - target: ${PORT}
        published: ${PORT}
    volumes:
      - ./:/usr/src/app