name: Continuous_Deployment_Dev_Server

on:
  push:
    branches:
      - dev
    paths:
      - 'server/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run deploy script on AWS prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SSH_HOST_DEV }}
          username: ${{ secrets.AWS_SSH_USER_DEV }}
          key: ${{ secrets.AWS_SSH_PEM_KEY_DEV }}
          script: |
            set -e
            ./dev_deploy.sh
