name: Continuous_Deployment_Prod_Server

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run deploy script on AWS prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SSH_HOST_PROD }}
          username: ${{ secrets.AWS_SSH_USER_PROD }}
          key: ${{ secrets.AWS_SSH_PEM_KEY_PROD }}
          script: |
            set -e
            cd ~/lucky-parking/server
            ./deploy.sh
